services:
  store:
    build:
      context: .
      dockerfile: 'Dockerfile'
    image: 'megatech-store'
    depends_on:
      db:
        condition: 'service_healthy'
    container_name: 'store'
    ports:
      - '8080:8080'
  db:
    container_name: 'db'
    image: postgres:16.4
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      retries: 5
      start_period: 5s
    ports:
      - '5432:5432'