services:
  store:
    container_name: dev-store
    env_file:
      - .env.devlopment.local
  db:
    container_name: dev_db
    env_file:
      - .env.devlopment.local
    volumes:
     - dev-data:/var/lib/postgresql/data
volumes:
  dev-data: