services:
  store:
    container_name: megatech-store
    env_file:
      - .env
  db:
    container_name: prod_db
    env_file:
      - .env
    volumes:
      - prod-data:/var/lib/postgresql/data
volumes:
  prod-data:
