spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://${DB_HOST:localhost}:5432/${POSTGRES_DB:prod}?serverTimezone=UTC
    username: ${POSTGRES_USER:postgres}
    password: ${DB_PASSWORD:postgres}
  flyway:
    locations: 'classpath:db/migration/prod'
    validate-on-migrate: true