spring:
    datasource:
        driver-class-name: org.postgresql.Driver
        url: jdbc:postgresql://${DB_HOST:localhost}:5432/${POSTGRES_DB:dev}
        username: ${POSTGRES_USER:postgres}
        password: ${DB_PASSWORD:postgres}
    flyway:
        locations: 'classpath:db/migration/dev'
        validate-on-migrate: true